name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/shell-ci.yaml@bbb84133e2512f24cf9e89fc67d43d378d299360 # v1
    with:
      shellcheck-paths: "./*.sh"
